name: terraform_apply

on:
  workflow_call:
    inputs:   
      job_name:
        required: false
        type: string
        default: 'Terraform Apply'
      runs_on:
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  terraform-apply:
    name: ${{ inputs.job_name }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: terraform init
        id: init
        run: terraform init -input=false
        working-directory: ${{ env.working_directory}}

      - name: terraform apply
        id: apply
        run: terraform apply -input=false -auto-approve
        working-directory: ${{ env.working_directory }}