parameters:
  - name: jobName
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""

stages:
  - stage: CodeQualityChecks
    displayName: "Code Quality Check"
    jobs:
      - job: LintingChecks
        displayName: ${{ parameters.jobName }}
        steps:
          - task: NodeTool@0
            displayName: "Setup Node.JS Environment"
            inputs:
              versionSource: "spec"
              versionSpec: "20.x"

          - task: Bash@3
            displayName: "Install Dependencies"
            inputs:
              targettype: "inline"
              script: npm ci
              workingDirectory: ${{ parameters.workingDirectory}}

          - task: Bash@3
            displayName: "Java Script Linting (Biome)"
            inputs:
              targetType: "inline"
              script: |
                npm install -g @biomejs/biome
                biome lint ./src
              workingDirectory: ${{ parameters.workingDirectory }}
            continueOnError: true

          - task: Bash@3
            displayName: "CSS Linting (Stylelint)"
            inputs:
              targetType: "inline"
              script: |
                npm install -g stylelint stylelint-config-standard
                stylelint "src/**/*.css"
              workingDirectory: ${{ parameters.workingDirectory }}
            continueOnError: true

          - task: Bash@3
            displayName: "README Linting (Markdownlint)"
            inputs:
              targetType: "inline"
              script: |
                npm install -g markdownlint-cli
                markdownlint "**/*.md" --ignore node_modules
              workingDirectory: ${{ parameters.workingDirectory }}
            continueOnError: true
