parameters:
  - name: jobName
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""

stages:
  - stage: CodeQualityChecks
    displayName: "Code Quality Check"
    jobs:
      - job: LintingChecks
        displayName: ${{ parameters.jobName }}
        steps:
          - task: NodeTool@0
            displayName: "Setup Node.JS Environment"
            inputs:
              versionSource: "spec"
              versionSpec: "20.x"

          - task: Bash@3
            displayName: "Java Script Linting - Biome"
            inputs:
              targetType: "inline"
              script: biome lint ./src
              workingDirectory: ${{ parameters.workingDirectory }}
            continueOnError: true

          - task: Bash@3
            displayName: "CSS Linting (Stylelint)"
            inputs:
              targetType: "inline"
              script: stylelint ./src --config stylelint.config.mjs
              workingDirectory: ${{ parameters.workingDirectory }}
