parameters:
  - name: jobName
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""

stages:
  - stage: SoftwareCompositionAnalysis
    displayName: 'Software Composition Analysis'
    jobs:
      - job: DependancyVulnerabilitySecurity
        displayName: ${{ parameters.jobName }}
        steps:

          - task: Bash@3
            displayName: 'Install Dependencies'
            inputs:
              targettype: 'inline'
              script: npm ci
              workingDirectory: ${{ parameters.workingDirectory}}
          
          - task: Bash@3
            displayName: 'RetireJs Scan'
            inputs:
              targetType: 'inline'
              script: |
                mkdir -p report
                retire --path . --outputpath report/retirejs.json
              workingDirectory: ${{ parameters.workingDirectory}}

          - task: Bash@3
            displayName: 'Convert RetireJS report to Sarif'
            inputs:
              targetType: 'inline'
              script: node scripts/retire-to-sarif.js
              workingDirectory: ${{ parameters.workingDirectory}}

          - task: PublishCodeAnalysisResults@1
            displayName: 'Publish RetireJS Scan Report'
            inputs:
              CodeAnalysisTool: Sarif
              SarifFile: ${{ parameters.workingDirectory}}/report/retirejs.sarif
