parameters:
  - name: jobName
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""

stages:
  - stage: SoftwareCompositionAnalysis
    displayName: 'Software Composition Analysis'
    jobs:
      - job: DependancyVulnerabilitySecurity
        displayName: ${{ parameters.jobName }}
        steps:

          - task: Bash@3
            displayName: 'Install Safety Tool'
            inputs:
              targetType: 'inline'
              script: |
                pip --version
                pip install Safety
              workingDirectory: ${{ parameters.workingDirectory }}

          - task: Bash@3
            displayName: 'Safety Scan'
            inputs:
              targetType: 'inline'
              script: safety scan .
              workingDirectory: ${{ parameters.workingDirectory }}
