parameters:
  - name: sonarHost
    type: string
    default: ""

  - name: sonarToken
    type: string
    default: ""

  - name: sonarProject
    type: string
    default: ""

  - name: workingDirectory
    type: string
    default: ""
  
  - name: jobName
    type: string
    default: ""

stages:
  - stage: StaticCodeAnalysis
    displayName: "Static Code Analysis"
    jobs:
      - job: SonarqubeAnalysis
        displayName: ${{ parameters.jobName }}
        steps:
          - task: Bash@3
            displayName: "Sonarqube Scan"
            inputs:
              targetType: "inline"
              script: |
                sonar-scanner \
                -D sonar.host.url=${{ parameters.sonarHost }} \
                -D sonar.token=${{ parameters.sonarToken }} \
                -D sonar.projectKey=${{ parameters.sonarProject }} \
                -Dsonar.qualitygate.wait=true
              workingDirectory: ${{ parameters.workingDirectory }}
